# Generated by Django 5.0.2 on 2024-03-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_galleryindexpage_gallerytagindexpage_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallerypage",
            name="intro",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
